### ISSUE TITLE
Allow to reroll some of the properties

### ISSUE THREAD

**Issue by ogregoire** [Cellule/dndGenerator#13]
Please allow to reroll only some properties of a rolled character.

For instance, I roll  a character, I like it, but the plot hook doesn't suit me, and I would like to have other plots that are in line with the rest of the character.

It can be the plot hook, or the hair or the personality, or anything else...

**Comment by etiens** [comment]
Since so many things are linked, and with the way we generate characters right now, this isn't doable.
And to be honest, the parts you "don't like" at first usually end up making the best characters when you need to find ways to explain them or make them work.
