### ISSUE TITLE
Export to Json/Txt

### ISSUE THREAD

**Issue by Cellule** [Cellule/dndGenerator#2]
Add a button to export the current npc to json or text format.
Any other format ?

**Comment by blackpan2** [comment]
If it can be exported to JSON in a clear enough manner (like all of the parts are broken out in acceptable tags) then the format should be good enough for any other sort of tool that would be importing it. 

This is curious to me and I am going to look into making a tool that will take JSON in and then make the [homebrewery](http://homebrewery.naturalcrit.com/) markup for someone so they can easily drop that into the editor and make a nice little page out of it

**Comment by Cellule** [comment]
As of right now we can't export an npc. However, you can make a request to
http://npcgenerator.azurewebsites.net/_/npc
and it will generate a random npc and give you back the json format for it.
However, this api is undocumented and could change at anytime. (We don't have plans to change it anytime soon though)

Here's an example
```json
{
  "description": {
    "name": "Cedric Woodleaf",
    "age": 18,
    "gender": "male",
    "race": "human",
    "occupation": "jailer",
    "pronounMinus": "he ",
    "pronounCapit": "He "
  },
  "physical": {
    "hair": "a bald head",
    "eyes": "red eyes",
    "skin": "silky, ghostly white skin",
    "height": 180,
    "build": "a lean build",
    "face": "an oval, average face",
    "special": "He has a small piercing on his nose and he is albino."
  },
  "alignment": {
    "good": -1,
    "moralneutral": 2,
    "evil": 2,
    "lawful": 7,
    "ethicalneutral": 0,
    "chaotic": -1
  },
  "relationship": {
    "orientation": "Straight",
    "status": "Married"
  },
  "religion": {
    "description": "He openly worships Kelemvor, God of death and the dead. (Lawful Neutral)"
  },
  "ptraits": {
    "traits1": "He is an hopeless romantic. ",
    "traits2": "He is a perfectionist. "
  },
  "pquirks": {
    "description": "He knows all the gossip around town. "
  },
  "hook": {
    "description": "He needs help fighting a rebellious organization who wants to take control of the clergy."
  },
  "abilities": {
    "str": 15,
    "dex": 11,
    "con": 16,
    "int": 10,
    "wis": 11,
    "cha": 12
  }
}
```

**Comment by etiens** [comment]
Added a button to download a txt version of the NPC displayed! Enjoy :D
