### ISSUE TITLE
printable sheet - Could use Bootstrap 4

### ISSUE THREAD

**Issue by andrew-oxenburgh** [Cellule/dndGenerator#34]
It'd be great to be able to print these characters on a single sheet of paper.

BS4 provides classes for this, bubt it needs porting.

I'm happy to do this, but it could also need SCSS rather than LESS.

**Comment by Cellule** [comment]
I'd love help on this, I haven't much time to invest on this, been wanting to port less to scss for a while

**Comment by Cellule** [comment]
I've long updated to scss and bootstrap 5, would be possible to look into this
