### ISSUE TITLE
Ubtau seems to be the most popular deity by far

### ISSUE THREAD

**Issue by geoidesic** [Cellule/dndGenerator#39]
Secretly worships Ubtau – this comes up on virtually every second character. It would be nice to occasionally see some other deities being worshipped.

**Comment by etiens** [comment]
That's weird. Are your characters the same race? There is a wide variety of gods, but it is smaller for some of the races that are said to primarily worship a specific god.

**Comment by etiens** [comment]
I just rolled at least 50 characters and Ubtau showed up only twice, maybe you're simply really luck? It _is_ random after all.
