### ISSUE TITLE
Wrong ability score calculations

### ISSUE THREAD

**Issue by SirFlau** [Cellule/dndGenerator#40]
Ability scores result in wrong ability modifiers.

Sample generated scores:

Strength | 17 [+4] (should be +3)
Dexterity | 16 [+3]
Constitution | 16 [+3]
Intellect | 14 [+2]
Wisdom | 15 [+3] (should be +2)
Charisma | 13 [+2] (should be +1)

**Comment by robbinghope** [comment]
I just noticed this issue too! The formula is incorrect for odd number ability scores. The formula for determining modifiers should be to subtract 10 from the ability score and then divide the total by 2 (round down). The full table can be seen below. 
![image](https://user-images.githubusercontent.com/25065833/107068379-86e42080-67ae-11eb-92ed-19e6a7804f8f.png)

**Comment by robbinghope** [comment]
Found the offending line: https://github.com/Cellule/dndGenerator/blob/ea1a2717677decef8d102a8e8694063dfc04fe04/src/NpcData.tsx#L26

Should use `Math.floor()` instead of `Math.round()`

**Comment by Cellule** [comment]
Closed by #41
