### ISSUE TITLE
Self contained application 

### ISSUE THREAD

**Issue by Dethras** [Cellule/dndGenerator#80]
If it is not such a hassle could you please make a self-contained .exe (Like electron) or something so that I could run a local server without having to install node or anything else, because sometimes connecting to the internet is a bit difficult. Thank you

**Comment by Cellule** [comment]
I doubt I'll spend time on this one anytime soon.
The website doesn't need internet to generate new sheets, everything runs locally directly on the browser so you could just "save" the website's html files and open that while offline.
I just gave it a try with `ctrl+s` then open the saved html and it mostly worked (some background images weren't saved locally)

**Comment by Dethras** [comment]
@Cellule - That is perfect, my apologies I didn't expect it to be this easy.
