### ISSUE TITLE
Request: Copy to clipboard

### ISSUE THREAD

**Issue by Dethras** [Cellule/dndGenerator#82]
Could you please add a "Copy to clipboard" functionality, since it would be very useful to import into OneNote or other programs

**Comment by Cellule** [comment]
You could export the sheet using the "export" button then copy the content of the .txt file

**Comment by Dethras** [comment]
The idea is to ease the process during a session, since I primary use this during my dnd sessions, and would want to copy the stat block into my OneNote. And it would be far easier to just hit a button that will copy the data, and I just paste it into OneNote, rather than having to go through the current flow: download -> open -> copy -> paste . Having said that I made the changes, and I will open a pull request tomorrow and see if you approve the changes.
